import { Geist, Geist_Mono, Anton, Satisfy } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
});

const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Rahul Shaw",
  description: "Generated by create next app",
  icons: {
    icon: "/myphoto.png", // 
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${satisfy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
